// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9Thg-pJn84qGKBBBtz2IzDG0NHq9uA4',
    appId: '1:186919330891:web:d73ecde759fb9e46cb99ce',
    messagingSenderId: '186919330891',
    projectId: 'newversity-56827',
    authDomain: 'newversity-56827.firebaseapp.com',
    storageBucket: 'newversity-56827.appspot.com',
    measurementId: 'G-L1E5R1DLL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3J6kvy2B_7wvnfaQqA8lVgjsWqJBWWVA',
    appId: '1:186919330891:android:6e677ddc0fe3d2f6cb99ce',
    messagingSenderId: '186919330891',
    projectId: 'newversity-56827',
    storageBucket: 'newversity-56827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqOI-CJ_K7K5fYWV2b28NBsNBeBKBCrs4',
    appId: '1:186919330891:ios:55dbc001c8143bf8cb99ce',
    messagingSenderId: '186919330891',
    projectId: 'newversity-56827',
    storageBucket: 'newversity-56827.appspot.com',
    androidClientId: '186919330891-omkephplk3ra6nag2m7g7hvf6t7v6qdt.apps.googleusercontent.com',
    iosClientId: '186919330891-hcfpn9nc5vncqiab1p7vu4relboo6vu9.apps.googleusercontent.com',
    iosBundleId: 'com.newversity.newversity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqOI-CJ_K7K5fYWV2b28NBsNBeBKBCrs4',
    appId: '1:186919330891:ios:55dbc001c8143bf8cb99ce',
    messagingSenderId: '186919330891',
    projectId: 'newversity-56827',
    storageBucket: 'newversity-56827.appspot.com',
    androidClientId: '186919330891-omkephplk3ra6nag2m7g7hvf6t7v6qdt.apps.googleusercontent.com',
    iosClientId: '186919330891-hcfpn9nc5vncqiab1p7vu4relboo6vu9.apps.googleusercontent.com',
    iosBundleId: 'com.newversity.newversity',
  );
}
